### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by lxbarth** [openstreetmap/mapnik-stylesheets#15]
Is this project current at all in the light of [openstreetmap-carto](http://blog.openstreetmap.org/2013/08/05/new-rendering-cartocss-stylesheet/) deployed on osm.org?
- README needs to reflect the legacy status of this project
- README should reference successor: https://github.com/gravitystorm/openstreetmap-carto/issues/135

**Comment by gravitystorm** [comment]
This is actually a mirror of the repository at https://trac.openstreetmap.org/browser/subversion/applications/rendering/mapnik/

I don't know if anyone who commits to svn follows the issues here on github though.

**Comment by gravitystorm** [comment]
At the very least, we should update the repo description. "Mirror of the mapnik stylesheets used on OpenStreetMap.org" is misleading, since the stylesheets aren't used on osm.org any more.

**Comment by gravitystorm** [comment]
This is now fixed - both the repo description and README have been updated (thanks to @tomhughes and @harry-wood . 

(But I can't close the issue)
