### ISSUE TITLE
Fairway needs to be rendered a different color from the green.

### ISSUE THREAD

**Issue by davidgumberg** [openstreetmap/mapnik-stylesheets#20]
Golf fairways should be rendered differently from the golf green, but they are not, leading to handful of examples I have found of people tagging for the renderer.

**Comment by floscher** [comment]
You probably wanted to report this issue against the current standard-style on http://osm.org which is maintained at [gravitystorm/openstreetmap-carto](https://github.com/gravitystorm/openstreetmap-carto).
There is already an issue about golf=fairway over there: gravitystorm/openstreetmap-carto#661
