### ISSUE TITLE
blended array: world_boundaries

### ISSUE THREAD

**Issue by ghost** [openstreetmap/mapnik-stylesheets#4]
$ ./generate_xml.py --dbname osm --user postgres --password password --accept-none
{'dbname': 'osm', 'host': '', 'user': 'postgres', 'extent': '-20037508,-19929239,20037508,19929239', 'password': 'password', 'port': '', 'estimate_extent': 'false'}
Traceback (most recent call last):
  File "./generate_xml.py", line 174, in <module>
    validate(blended,parser)
  File "./generate_xml.py", line 90, in validate
    if not os.path.exists(params['world_boundaries']):
KeyError: 'world_boundaries'
osm@NL-Map:~/mapnik-style$ python
Python 2.7.3 (default, Apr 20 2012, 22:39:59)
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import os
> > > os.path.exists('world_boundaries')
> > > True

I think that the "blended" array (at line 173) isn't picking up the 'world_boundaries' properly.

**Comment by SebastienTr** [comment]
Hello !
I have the same issue, know you how to manage it ?
Thank's ;)
