### ISSUE TITLE
Can changes be contributed here?

### ISSUE THREAD

**Issue by tmcw** [openstreetmap/mapnik-stylesheets#5]
Is this repository capable of being synced up to the SVN repo? Are there any plans (please, god, I hope) to use 'just git' for this and not have to deal with SVN for this project?

**Comment by avar** [comment]
The guys who write the mapnik stylesheets aren't responsible for this mirror, they can be contacted on the osm dev list.

I don't know if they have any plans to move their work to git.

You can clone this repo and use it to send them patches, or ask them to port the repo to git / offer to help them with that.

I'd be happy to hand this repo over to them if they want to make it canonical.
